name = "discocks"
compatibility_date = "2024-07-23"
pages_build_output_dir = ".svelte-kit/cloudflare"

[placement]
mode = "smart"

[env.preview.vars]
NODE_VERSION = "20"
PNPM_VERSION = "9"

[env.production.vars]
NODE_VERSION = "20"
PNPM_VERSION = "9"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "discocks-dev"
database_id = "ed9345ed-80f4-4440-aac4-b6335bc779c2"
migrations_dir = "./drizzle/migrations"

[[env.production.d1_databases]]
binding = "DB"
database_name = "discocks-prod"
database_id = "0f11ac13-3502-4336-a206-52df0856d11d"
migrations_dir = "./drizzle/migrations"
