name = "discocks"
compatibility_date = "2024-07-23"
pages_build_output_dir = ".svelte-kit/cloudflare"

[placement]
mode = "smart"

[env.preview.vars]
NODE_VERSION = "20"
PNPM_VERSION = "9"

[env.production.vars]
NODE_VERSION = "20"
PNPM_VERSION = "9"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "discocks"
database_id = "b6f47314-0051-48f1-8b95-3640f0eb0569"
migrations_dir = "./drizzle/migrations"
