// Generated by Wrangler on Tue Jul 23 2024 19:31:53 GMT+0200 (Mitteleuropäische Sommerzeit)
// by running `wrangler types --env preview`

interface Env {
	NODE_VERSION: '20';
	PNPM_VERSION: '9';
	DB: D1Database;
}
